[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "google-api-python-client>=2.177.0",
    "lurk>=0.1.3",
    "pycryptodome>=3.23.0",
    "requests>=2.32.4",
]
